main: iomatix.spigot.rpgleveledmobs.Main
softdepend: [MobArena,SkillAPI]
name: RPGLeveledMobs
version: 0.1a
author: iomatix
description: Leveled mobs with scaling attributes compatible with many RPG plugins.
commands:
  rpgmobs:
    description: Opens RPG Level Mobs configuration interface.
    usage: /rpgmobs
    permission: rpgleveledmobs.gui
    permission-message: You don't have the myplugin.mycommand permission.