main: iomatix.spigot.rpgleveledmobs.Main
softdepend: [MobArena, Heroes, LegendQuest, SkillAPI]
load: POSTWORLD
name: RPGLeveledMobs
version: 0.1a
api-version: 1.14
author: iomatix
description: Leveled mobs with scaling attributes compatible with many RPG plugins.
commands:
  rpgmobs:
    description: RPG Level Mobs command prefix.
    usage: /rpgmobs
    permission: rpgleveledmobs.admin
    permission-message: You don't have the myplugin.mycommand permission.